services:
  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline_dev:
    build: . 
    container_name: pipeline_dev
    # Keep it alive forever
    command: sleep infinity
    volumes:
      # Map the WHOLE project to /workspace
      - .:/workspace
    working_dir: /workspace
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    # Single source of truth for variables
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      # For python scripts
      - POSTGRES_HOST=postgres

volumes:
  my_pgdata: {}
